### ISSUE TITLE
Host notification is wrong

### ISSUE THREAD

**Issue by sykp241095** [khera/slack-integrations#2]
![image](https://cloud.githubusercontent.com/assets/1237528/7951805/8d4635d2-09de-11e5-910d-7d42d25728bf.png)

**Comment by khera** [comment]
What steps did you take to make it happen? It looks like nagios did not expand those variables on the second alert and passed them as literal values instead.

**Comment by sykp241095** [comment]
My config is like this:

```
  define command {
    command_name    notify-slack
    command_line    /usr/local/sbin/slack-nagios-notify -C $CONTACTEMAIL$ -t "$NOTIFICATIONTYPE$" -a "$HOSTALIAS$" -d "$SERVICEDESC$" -w "$SHORTDATETIME$" -s "$SERVICESTATE$" -o "$SERVICEOUTPUT$" -u "$SERVICEACKAUTHOR$" -c "$SERVICEACKCOMMENT$"
  }

  define command {
    command_name    host-notify-slack
    command_line    /usr/local/sbin/slack-nagios-notify -C $CONTACTEMAIL$ -t "$NOTIFICATIONTYPE$" -a "$HOSTALIAS$" -d "host" -w "$SHORTDATETIME$" -s "$SERVICESTATE$" -o "$SERVICEOUTPUT$" -u "$SERVICEACKAUTHOR$" -c "$SERVICEACKCOMMENT$"
  }

 define contact {
   name                    slack
   service_notification_period     24x7
   host_notification_period        24x7
   service_notification_options    w,u,c,r
   host_notification_options       d,u,r
   service_notification_commands   notify-slack
   host_notification_commands      host-notify-slack
   register                        0
 }

define contact {
   use slack
   contact_name sysadmin-slack
   email  \#sysadmin
}


service {
     .........
}
```

some config above was copied from doc of script slack-nagios-notify.

**Comment by khera** [comment]
I do not think "host" notifications have defined the variables `$SERVICESTATE$` and `$SERVICEOUTPUT$` in the nagios macros.

What you're seeing is that nagios is not substituting values for those variables when issuing your `host-notify-slack` notification, and then this script just blindly sends the literal string `$SERVICEOUTPUT$` that nagios gave it.
